config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'dashboard#show'
  root 'welcome#index'
  resources :stations
  resources :welcome, only: [:index, :create]
end

# resources :users, path: "", param: :slug
#
# namespace :users, as: :user, path: "/:slug" do
#   resources :trips
#   get '/dashboard', to: 'dashboard#show'
# end

app/models/alt_fuel.rb
class AltFuel < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  # attr_accessible: :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode # :if => :address_changed?
end

app/models/station.rb
class Station < ActiveRecord::Base

  def self.service
    @service ||= StationService.new
  end

  def self.all
    service.stations["fuel_stations"].map do |station|
      _build_object(station)
    end
  end

  def self.find(id)
    _build_object(service.station(id))
  end

  def self.find_closest
    service.closest_stations["fuel_stations"].map do |station|
      _build_object(station)
    end
  end

  def self.find_closest_to_route
    service.routed_stations["fuel_stations"].map do |station|
      _build_object(station)
    end
  end

  def self._build_object(data)
    OpenStruct.new(data)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)

    user.email      = auth.info.email
    user.full_name  = auth.info.name
    user.first_name = auth.info.first_name
    user.last_name  = auth.info.last_name
    user.image_url  = auth.info.image
    user.uid        = auth.uid
    user.token      = auth.credentials.token
    user.save

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    redirect_to root_path unless current_user
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize!

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#  def new
#   @user = User.new
#  end

  def create
    user = User.find_or_create_from_auth(auth)
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    # flash[:success] = "Successful logout"
    session.clear
    redirect_to root_path
  end

private

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def show
    @station = Station.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def create
    # session[:latitude] = params[:latitude]
    # session[:longitude] = params[:longitude]
  end

  def index
    # @stations = Station.all
    @closest_stations_to_route = Station.find_closest_to_route
    # @alt_fuels = AltFuel.all
    @closest_stations = Station.find_closest
    # (session[:latitude], session[:longitude])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def fuel_color_helper(fuel_type)
    case fuel_type
      when "BD"
      "#FFA500" #Orange
      when "CNG"
      "#FFFFFF" #White
      when "E85"
      "#000000" #Black
      when "ELEC"
      "#0000FF" #Blue
      when "HY"
      "#FFFF00" #Yellow
      when "LNG"
      "#008000" #Green
      else "LPG"
      "#FF0000" #Red
    end
  end

end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/application/_closest_stations.html.erb
<h3> Closest Charging Stations: </h3>
  <% @closest_stations.each do |station| %>
<div class="closest_stations container col-md-12">
    <b><%= station.station_name %>: <%= station.fuel_type_code %></b><br>
    <b>Address:</b> <%= station.street_address %>,
    <%= station.city %>, <%= station.state %> <%= station.zip %><br>
    <b>Phone:</b> <%= station.station_phone %><br>
    <b>Distance from current location:</b> <%= station.distance %> miles <br>
    <%= link_to 'View Details', station_path(station.id)%>
</div>
  <% end %>

app/views/application/_facebook.html.erb
<div id="facebook" class="footer">
  <nav>
    <ul>
      <li id="navbar-right" class="navbar-collapse collapse">
      <% if current_user.nil? %>
        <a href="/auth/facebook" class="btn btn-block btn-social btn-lg btn-facebook" onclick="_gaq.push(['_trackEvent', 'btn-social', 'click', 'btn-lg']);"><i class="fa fa-facebook"></i>Sign in with Facebook</a>
      <% end %>
      </li>
      <li id="navbar-right" class="navbar-collapse collapse">
        <% if current_user %>
        <%= link_to('Logout', logout_path, :method => :delete, class: "btn btn-lg btn-default btn-home") %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

<div id="hey-good-lookin">
  <% if current_user %>
    <h1 class="home">Hey, good looking <%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %></h1>
  <% end %>
</div>

app/views/application/_map.html.erb
<div class='map' id='map'>
  <script>
// var L = require('leaflet');
// require('leaflet-routing-machine'); // Adds L.Routing onto L
// require('lrm-mapbox');

L.mapbox.accessToken = 'pk.eyJ1IjoiY2x1aHJpbmciLCJhIjoiNWF2Z1l6ZyJ9.8peAq7kTQyvXShlVv1K82w';
// L.mapbox.accessToken = '<%= Rails.application.secrets.mapbox_token %>';
// L.mapbox.accessToken = "ENV['facebook_secret']";
var map = L.mapbox.map('map', 'cluhring.lc04leg6')

var myLayer = L.mapbox.featureLayer().addTo(map);

var geojsonFeatures = [
  <% @closest_stations_to_route.each do |station| %>
  {
  "type": "Feature",
  "properties": {
    "url":"<%= request.env['HTTP_HOST']%>/stations/<%= station.id %>",
    "marker-symbol":"fuel",
    "marker-size":"medium",
    "marker-color": "<%= fuel_color_helper(station.fuel_type_code) %>",
    "stationDetails": "<%= station.station_name %><br><%= station.street_address %>, <%= station.city %>, <%= station.state %> <%= station.zip %>"
    // "icon": {
    //   "iconUrl": 'https://pbs.twimg.com/profile_images/444146105312243712/EHdy1GyV_400x400.png',
    //   "iconSize": [48, 48]
    // }
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      <%= station.longitude %>,
      <%= station.latitude %>
      ]
  }
},
<% end %>
];

myLayer.on('layeradd', function(e) {
  var marker = e.layer,
    feature = marker.feature;

  var popupContent =  '<a class="popup" href="http://' +
    feature.properties.url + '">' +
                          feature.properties.stationDetails +
                      '</a>';
  // if (feature.properties && feature.properties.popupContent) {
  marker.bindPopup(popupContent);
  // marker.bindPopup(feature.properties.url);
  // marker.setIcon(L.icon(feature.properties.icon));
});

myLayer.setGeoJSON(geojsonFeatures);

// <#% @alt_fuels.each do |alt_fuel| %>
// var <#%= alt_fuel.name %> = new L.LayerGroup();
// <#% end %>
//
// var overlays = {
// <#% @alt_fuels.each do |alt_fuel| %>
// "<#%= alt_fuel.name %>": <#%= alt_fuel.name %> ,
// <#% end %>
// };

var ctrl = L.Routing.control({
    waypoints: [
      L.latLng (39.749747, -104.999977),
      L.latLng (41.87, -87.63)
    ],
    routeWhileDragging: true,
    draggableWaypoints: true,
    geocoder: L.Control.Geocoder.nominatim()
}).addTo(map);

L.DomEvent.on(L.DomUtil.get('clear-wps'), 'click', function() {
    ctrl.setWaypoints([]);
});

// L.Control.geocoder().addTo(map);

// L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
//     attribution: '© OpenStreetMap contributors'
// }).addTo(map);


// L.geoJson(geojsonFeatures, {
//   filter: function(feature, layer) {
//     return feature.properties.show_on_map;
//   }
// }).addTo(map);


map.locate();

function onLocationFound(e) {
  var radius = e.accuracy / 2;
  var current_lat = e.latlng.lat;
  var current_long = e.latlng.lng;
  $.ajax ({
    data: { latitude: current_lat, longitude: current_long },
    type: 'post',
    url: '/welcome'
  });
  L.marker(e.latlng).addTo(map)
  .bindPopup("You are here").openPopup();

  L.circle(e.latlng, radius).addTo(map);
}

map.on('locationfound', onLocationFound);

</script>
</div>
<!-- <button id="clear-wps" type="button">Clear</button> -->

app/views/application/_modal.html.erb
<div class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-heading">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="#" class="btn btn-primary">Add to Cart</a>
  </div>
</div>

app/views/application/_nav_bar.html.erb
<div class="header">
<div class="row">
  <div class= "container col-md-3" id='logo'>
    <h3>
      <a id="navbar-left" class="navbar-collapse collapse" href="/">Flux Capacitor</a>
    </h3>
    <%= image_tag "green_car5.jpg" %>
  </div>
  <div class="col-md-9">
  </div>
</div>
</div>

app/views/application/_routing_info.html.erb
<div class='address-search' id="address1">
  <%= form_tag("/welcome", method: "create") do %>
  <%= label_tag("Starting Point") %><br>
  <%= text_field_tag "start_address", "Address, City, State, and/or Zip",
  :onclick => 'if($(this).val()=="Address, City, State, and/or Zip"){$(this).val("");};' %>
  <%= label_tag("Ending Point") %><br>
  <%= text_field_tag "end_address", "Address, City, State, and/or Zip",
  :onclick => 'if($(this).val()=="Address, City, State, and/or Zip"){$(this).val("");};' %><br>
  <button id="bb" type="submit" class="btn btn-default">Map It Out!</button>
  <% end %>
  <button id="aa" class="btn btn-default">Add Another Destination</button><br>
</div>

<script>
$(document).ready(function(){

  $("#aa").click(function(){

    $('#start_address').after("<p id='stopping_point'><label for='Starting_Point'>Stopping point</label><input type='text' class='input-large' name='map_address' id='map_address' value='Address, City, State, and/or Zip' onclick='if($(this).val()==&quot;Address, City, State, and/or Zip&quot;){$(this).val(&quot;&quot;);};''>"+
    "<input type='submit' value='' class='stop_point' id='removeStoppingPoint'></p>");

    $("#removeStoppingPoint").on('click', function(){
      $(this).closest('p').remove();

  });
  });
});

  // $(".map").height( $(".address-search").height() );

// $('#bb').click(function(){
//   if($('#map_address2').val()=="Address, City, State, and/or Zip"){
//     $('#map_address2').remove();
//   };
// });
</script>

app/views/dashboard/show.html.erb
<%= render partial: "nav_bar" %><br><br>
<div class="container-fluid container-home col-md-12">
    <h1 class="home">Hey, good looking <%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %></h1>
</div>
<div class="trip-tables">
<h2>Past Trips</h2>
<table class="table">
  <tr><th></th><th>Starting Point</th><th>Ending Point</th><th>Distance Traveled</th><th>Date Completed</th><th>Pictures</th></tr>
    <tr>
      <td>
      </td>
      <td>
      </td>
      <td>
      </td>
      <td>
      </td>
      <td>
      </td>
    </tr>
</table>

<h2>Future Trips</h2>
<table class="table">
  <tr><th></th><th>Starting Point</th><th>Ending Point</th><th>Distance Traveled</th><th>Departure Date</th><th>Pictures</th></tr>
    <tr>
      <td>
      </td>
      <td>
      </td>
      <td>
      </td>
      <td>
      </td>
      <td>
      </td>
    </tr>
</table>
</div>

<!-- <div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FluxCapacitor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <title>Flux Capacitor Map</title>
  <%= csrf_meta_tags %>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
  <link rel="stylesheet" href="leaflet-routing-machine.css" />
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.css' rel='stylesheet' />
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
  <script src="leaflet-routing-machine.js"></script>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta charset=utf-8 />
</head>
<body>
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash-#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/stations/show.html.erb
<div class="row station-s">
  <div class="col-md-4"></div>
  <div class="station-show col-md-4">
    <h1>Station Info</h1>
    <% ["id", "fuel_type_code", "station_name", "street_address", "city", "state",
    "zip", "intersection_directions", "station_phone", "access_days_time", "cards_accepted",
    "bd_blends", "e85_blender_pump", "hy_status_link", "ng_fill_type_code", "ng_psi",
    "ng_vehicle_class", "ev_level1_evse_num", "ev_level2_evse_num", "ev_dc_fast_num",
    "ev_other_evse", "ev_network", "ev_network_web", ].each do |param| %>
    <b><%= param %>: </b><%= @station.alt_fuel_station[param] %><br>
    <% end %>
  </div>
  <div class="col-md-4"></div>
</div>
<div class="station-s"></div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="container closest_stats col-md-3">
    <%= render partial: "closest_stations" %>
  </div>
  <div class="col-md-9">
    <%= render partial: "map" %>
  </div>
</div>
<%= render partial: "facebook" %>
<%= render partial: "nav_bar" %>